export const WITHDRAWAL_CONSTANTS = {
  QR_EXPIRATION_HOURS: 12,
  QR_CODE_LENGTH: 6,
  MAX_QR_GENERATION_ATTEMPTS: 100,
  
  WITHDRAWAL_STATUS: {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    DENIED: 'DENIED'
  } as const,
  
  WITHDRAWAL_METHOD: {
    QR: 'QR',
    MANUAL: 'MANUAL'
  } as const,
  
  QR_ACTION: {
    APPROVE: 'APPROVE',
    DENY: 'DENY'
  } as const
};

export type WithdrawalStatus = typeof WITHDRAWAL_CONSTANTS.WITHDRAWAL_STATUS[keyof typeof WITHDRAWAL_CONSTANTS.WITHDRAWAL_STATUS];
export type WithdrawalMethod = typeof WITHDRAWAL_CONSTANTS.WITHDRAWAL_METHOD[keyof typeof WITHDRAWAL_CONSTANTS.WITHDRAWAL_METHOD];
export type QrAction = typeof WITHDRAWAL_CONSTANTS.QR_ACTION[keyof typeof WITHDRAWAL_CONSTANTS.QR_ACTION];